function ClassInformation() {
    return(
        <div>
            <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pharetra vel turpis nunc eget lorem. Sapien nec sagittis aliquam malesuada bibendum arcu. Nisl nunc mi ipsum faucibus. Rutrum quisque non tellus orci. Tortor pretium viverra suspendisse potenti. Ut aliquam purus sit amet luctus venenatis lectus magna fringilla. Turpis massa sed elementum tempus egestas sed sed risus. Quam adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus urna. Ut tristique et egestas quis ipsum. Consectetur adipiscing elit duis tristique sollicitudin nibh. Odio ut sem nulla pharetra diam. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum. Lorem mollis aliquam ut porttitor leo a diam sollicitudin. Imperdiet dui accumsan sit amet nulla.</div>
            <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pharetra vel turpis nunc eget lorem. Sapien nec sagittis aliquam malesuada bibendum arcu. Nisl nunc mi ipsum faucibus. Rutrum quisque non tellus orci. Tortor pretium viverra suspendisse potenti. Ut aliquam purus sit amet luctus venenatis lectus magna fringilla. Turpis massa sed elementum tempus egestas sed sed risus. Quam adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus urna. Ut tristique et egestas quis ipsum. Consectetur adipiscing elit duis tristique sollicitudin nibh. Odio ut sem nulla pharetra diam. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum. Lorem mollis aliquam ut porttitor leo a diam sollicitudin. Imperdiet dui accumsan sit amet nulla.</div>
            <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pharetra vel turpis nunc eget lorem. Sapien nec sagittis aliquam malesuada bibendum arcu. Nisl nunc mi ipsum faucibus. Rutrum quisque non tellus orci. Tortor pretium viverra suspendisse potenti. Ut aliquam purus sit amet luctus venenatis lectus magna fringilla. Turpis massa sed elementum tempus egestas sed sed risus. Quam adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus urna. Ut tristique et egestas quis ipsum. Consectetur adipiscing elit duis tristique sollicitudin nibh. Odio ut sem nulla pharetra diam. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum. Lorem mollis aliquam ut porttitor leo a diam sollicitudin. Imperdiet dui accumsan sit amet nulla.</div>
        </div>
    )
    
}

export default ClassInformation;